FROM openjdk:17-slim AS builder

WORKDIR /app

COPY pom.xml ./
RUN mvn clean package

COPY target/*.jar ./

FROM openjdk:17-slim

WORKDIR /app

COPY --from=builder ./app.jar ./

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
